### ISSUE TITLE
fs.writeFile callback missing

### ISSUE THREAD

**Issue by shark-o** [makovich/google-fonts-offline#10]
Getting error while running `goofoffline "https://fonts.googleapis.com/css?family=Source+Sans+Pro"`

`TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1156:14)
    at IncomingMessage.<anonymous> (/Users/sharko/Projects/JD/temp/web-apps/settings/node_modules/google-fonts-offline/index.js:182:16)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

Fixed when adding callback for fs.writeFile() at index.js:182 -> `fs.wrtieFile(..., ..., err => {})`

**Comment by makovich** [comment]
Thanks for unsuspending me. :^) As I understand, Node API have changed and there were a deprecation notice which I definitely was not aware of. I fixed this with sync version `writeFileSync`.
