### ISSUE TITLE
FontFacePattern bug

### ISSUE THREAD

**Issue by alexbowers** [makovich/google-fonts-offline#6]
```
goofoffline "https://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic"
```

Doesn't work for me

I get

```
Mimics to https://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic...
/usr/lib/node_modules/google-fonts-offline/index.js:121
            css.match(fontFaceRulePattern).forEach(processFontface);
                                          ^

TypeError: Cannot read property 'forEach' of null
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/google-fonts-offline/index.js:121:43)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

As my error.

I have tried it quoted and unquoted. Neither seem to work.

**Comment by alexbowers** [comment]
Nvm, fixed it. I was mapping fonts.googleapis.com in my hosts file
